name: 'S3 Compatible Upload'
description: 'Uploads files to an S3 compatible storage service using glob patterns.'
inputs:
  s3-access-key-id:
    description: 'S3 Access Key ID for authentication.'
    required: true
  s3-secret-access-key:
    description: 'S3 Secret Access Key for authentication.'
    required: true
  s3-endpoint:
    description: 'S3 compatible endpoint URL (e.g., `https://s3.example.com`).'
    required: true
  s3-bucket:
    description: 'S3 bucket name.'
    required: true
  files:
    description: 'Glob pattern for files to upload (e.g., `dist/**/*`).'
    required: true
  exclude:
    description: 'Glob pattern for files to exclude from upload (e.g., `**/*.tmp`).'
    required: false
    default: ''
  target-path:
    description: 'Target path in the S3 bucket (e.g., `uploads/`).'
    required: true
    default: '/'
  strip-path-prefix:
    description: 'Path prefix to strip from uploaded files (e.g., `dist/` will strip this prefix from all uploaded files).'
    required: false
    default: ''
  s3-region:
    description: 'S3 region (e.g., `us-east-1`).  Required for standard AWS S3, often optional for S3-compatible services.'
    required: false
  retry-count:
    description: 'Number of times to retry failed uploads before giving up.'
    required: false
    default: '3'
runs:
  using: 'node20'
  main: 'dist/index.js'
